### ISSUE TITLE
Reported seldepth is off by one

### ISSUE THREAD

**Issue by joergoster** [joergoster/Moonfish#2]
in mate in x positions.
Example:

> info depth 13 seldepth 10 multipv 1 score mate 5 nodes 5353 nps 1070600 tbhits 0 time 5 pv h4f4 e2f3 f4e3 f3h5 h7h5 d4f3 h5h1 f3g1 h1g1

I guess the reason is that we update `selDepth` even at checkmate nodes (no legal moves to make).

**Comment by penguingim1** [comment]
Hi @joergoster ,The new engine is ready for release, Why do you leave our organization? Are you interested in working with us?

Also, my account in Official_Stockfish has been restricted by the admins, that's why I couldn't answer you.
