### ISSUE TITLE
NN version please

### ISSUE THREAD

**Issue by leonhurricane** [joergoster/Moonfish#5]
In earlier Version you also Released a NN version of MoonFish was very great please add some new NN source code I need it for Android compilation.

**Comment by joergoster** [comment]
@leonhurricane This is not an issue with the code. Closing.

P.S. For requests like this please use a forum of your choice. Also note, that I never released Moonfish myself. That were other people, please contact them for a NN version (which has nothing to do with a Neural Network, of course)!
